# Generated by Django 3.0.6 on 2020-05-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images/pub/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pubcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images/pub_category/%Y/%m/%d/'),
        ),
    ]
