# Generated by Django 3.0.6 on 2020-05-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0003_auto_20200506_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='slug',
            field=models.SlugField(default=2, max_length=250, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
