# Generated by Django 3.0.6 on 2020-05-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0004_pub_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubcategory',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
